'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('newmile', {
  status: () => ipcRenderer.invoke('nm:status'),
  config: () => ipcRenderer.invoke('nm:config'),
  version: () => ipcRenderer.invoke('nm:version'),
  getSettings: () => ipcRenderer.invoke('nm:getSettings'),
  saveSettings: (s) => ipcRenderer.invoke('nm:saveSettings', s),
  testSamsara: (token) => ipcRenderer.invoke('nm:testSamsara', token),
  samsara: () => ipcRenderer.invoke('nm:samsara'),
  camera: (truckNum) => ipcRenderer.invoke('nm:camera', truckNum),
  route: (payload) => ipcRenderer.invoke('nm:route', payload),
  geocode: (q) => ipcRenderer.invoke('nm:geocode', q),
  ai: (payload) => ipcRenderer.invoke('nm:ai', payload),
  aiStatus: () => ipcRenderer.invoke('nm:aiStatus'),
  directory: () => ipcRenderer.invoke('nm:directory'),
  setOnCall: (list) => ipcRenderer.invoke('nm:setOnCall', list),
  drivers: () => ipcRenderer.invoke('nm:drivers'),
  hos: () => ipcRenderer.invoke('nm:hos'),
  calc: (name, args) => ipcRenderer.invoke('nm:calc', { name, args }),
  ocr: (image) => ipcRenderer.invoke('nm:ocr', { image }),
  scanPlan: () => ipcRenderer.invoke('nm:scanPlan'),
  sfOpen: () => ipcRenderer.invoke('nm:sfOpen'),
  zonasOpen: () => ipcRenderer.invoke('nm:zonasOpen'),
  sfBuild: (p) => ipcRenderer.invoke('nm:sfBuild', p),
  sfSend: (p) => ipcRenderer.invoke('nm:sfSend', p),
  sfSaveCsv: () => ipcRenderer.invoke('nm:sfSaveCsv'),
  sfPdf: () => ipcRenderer.invoke('nm:sfPdf'),
  readPlan: (dateISO) => ipcRenderer.invoke('nm:readPlan', { dateISO }),
  pickPlanFile: (dateISO) => ipcRenderer.invoke('nm:pickPlanFile', { dateISO }),
  truckNotes: (payload) => ipcRenderer.invoke('nm:truckNotes', payload),
  projectTrucks: (p) => ipcRenderer.invoke('nm:projectTrucks', p),
  rotationHistory: (date, days) => ipcRenderer.invoke('nm:rotationHistory', { date, days }),
  checkUpdate: () => ipcRenderer.invoke('nm:checkUpdate'),
  zoom: (factor) => ipcRenderer.invoke('nm:zoom', factor),
  sendDriverMsg: (p) => ipcRenderer.invoke('nm:sendDriverMsg', p),
  deleteAssignments: (ids) => ipcRenderer.invoke('nm:deleteAssignments', ids),
  logs: () => ipcRenderer.invoke('nm:logs'),
  connect: () => ipcRenderer.invoke('nm:connect'),
  resume: () => ipcRenderer.invoke('nm:resume'),
  disconnect: () => ipcRenderer.invoke('nm:disconnect'),
  refreshAll: (dateISO) => ipcRenderer.invoke('nm:refreshAll', dateISO),
  pullDay: (dateISO) => ipcRenderer.invoke('nm:pullDay', dateISO),
  orderAssignments: (orderId) => ipcRenderer.invoke('nm:orderAssignments', orderId),
  pushOrder: (payload) => ipcRenderer.invoke('nm:pushOrder', payload),
  reconcileSeq: (intentByTruck) => ipcRenderer.invoke('nm:reconcileSeq', intentByTruck),
  updateOrderQty: (orderId, quantity, flex) => ipcRenderer.invoke('nm:updateOrderQty', { orderId, quantity, flex }),
  fuel: (op, args) => ipcRenderer.invoke('nm:fuel', { op, args }),
  gpsVerify: (payload) => ipcRenderer.invoke('nm:gpsVerify', payload),
  gpsSaveLoc: (payload) => ipcRenderer.invoke('nm:gpsSaveLoc', payload),
  routeEta: (payload) => ipcRenderer.invoke('nm:routeEta', payload),
  googleStatus: () => ipcRenderer.invoke('nm:googleStatus'),
  downloadUpdate: () => ipcRenderer.invoke('nm:downloadUpdate'),
  onUpdate: (cb) => ipcRenderer.on('nm:update', (_e, u) => cb(u)),
  onStatus: (cb) => ipcRenderer.on('nm:status', (_e, st) => cb(st)),
  onLog: (cb) => ipcRenderer.on('nm:log', (_e, line) => cb(line))
});
